[project]
name="pumaplot"
version = "0.1.0"
requires-python=">=3.11"
dependencies = ["jupyter>=1.1.1", "nbdev>=2.4.2", "pre-commit>=4.2.0"]

[tool.ruff]
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "venv",
    "pumaplot/",
    "setup.py",
    "_modidx.py",
]

extend-include = ["*.ipynb"]

extend-select = ['I', 'N', 'PD']

line-length = 88
indent-width = 4

[tool.ruff.lint]
fixable = ["ALL"]

ignore = ["F403"]

dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

[tool.ruff.format]
quote-style = "double"

indent-style = "space"

skip-magic-trailing-comma = false

line-ending = "auto"
